KM_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('news/',include('news.urls')),
    path('board/',include('board.urls')),
    path('login/', include('log_app.urls')),
    path('my_page/',include('my_page.urls')),
    path('qnaboard/',include('qnaBoard.urls')),
    path('boormiboard/',include('boormiBoard.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
######################## 일반 게시판 ##############################
    path('free/', views.free_index, name='free_index'),
    path('free/answer/create/<int:postId>/', views.free_answer_create, name='free_answer_create'),
    path('free/answer/delete/<int:postId>/<int:answerId>/', views.free_answer_delete, name='free_answer_delete'),
    path('free/<int:postId>/', views.free_detail,name='free_detail'),
    path('free/write/', views.free_write, name='free_write'),
    path('free/delete/<int:postId>', views.free_boardDelete, name='free_delete'), # 수정함 : free를 붙임
    path('free/edit/<int:postId>', views.free_boardEdit, name='free_boardEdit'), # 수정함 : free를 붙임
######################## 공학 게시판 ##############################
    path('eng/', views.eng_index, name='eng_index'),
    path('eng/answer/create/<int:postId>/', views.eng_answer_create, name='eng_answer_create'),
    path('eng/answer/delete/<int:postId>/<int:answerId>/', views.eng_answer_delete, name='eng_answer_delete'),
    path('eng/<int:postId>/', views.eng_detail,name='eng_detail'),
    path('eng/write/', views.eng_write, name='eng_write'),
    path('eng/delete/<int:postId>', views.eng_boardDelete, name='eng_delete'), 
    path('eng/edit/<int:postId>', views.eng_boardEdit, name='eng_boardEdit'), 
######################## 자연과학 게시판 ##############################
    path('sci/', views.sci_index, name='sci_index'),
    path('sci/answer/create/<int:postId>/', views.sci_answer_create, name='sci_answer_create'),
    path('sci/answer/delete/<int:postId>/<int:answerId>/', views.sci_answer_delete, name='sci_answer_delete'),
    path('sci/<int:postId>/', views.sci_detail,name='sci_detail'),
    path('sci/write/', views.sci_write, name='sci_write'),
    path('sci/delete/<int:postId>', views.sci_boardDelete, name='sci_delete'), 
    path('sci/edit/<int:postId>', views.sci_boardEdit, name='sci_boardEdit'), 
######################## 의학/간호 게시판 ##############################
    path('med/', views.med_index, name='med_index'),
    path('med/answer/create/<int:postId>/', views.med_answer_create, name='med_answer_create'),
    path('med/answer/delete/<int:postId>/<int:answerId>/', views.med_answer_delete, name='med_answer_delete'),
    path('med/<int:postId>/', views.med_detail,name='med_detail'),
    path('med/write/', views.med_write, name='med_write'),
    path('med/delete/<int:postId>', views.med_boardDelete, name='med_delete'), 
    path('med/edit/<int:postId>', views.med_boardEdit, name='med_boardEdit'), 
######################## 예체능 게시판 ##############################
    path('art/', views.art_index, name='art_index'),
    path('art/answer/create/<int:postId>/', views.art_answer_create, name='art_answer_create'),
    path('art/answer/delete/<int:postId>/<int:answerId>/', views.art_answer_delete, name='art_answer_delete'),
    path('art/<int:postId>/', views.art_detail,name='art_detail'),
    path('art/write/', views.art_write, name='art_write'),
    path('art/delete/<int:postId>', views.art_boardDelete, name='art_delete'), 
    path('art/edit/<int:postId>', views.art_boardEdit, name='art_boardEdit'), 
######################## 인문/사회 게시판 ##############################
    path('soc/', views.soc_index, name='soc_index'),
    path('soc/answer/create/<int:postId>/', views.soc_answer_create, name='soc_answer_create'),
    path('soc/answer/delete/<int:postId>/<int:answerId>/', views.soc_answer_delete, name='soc_answer_delete'),
    path('soc/<int:postId>/', views.soc_detail,name='soc_detail'),
    path('soc/write/', views.soc_write, name='soc_write'),
    path('soc/delete/<int:postId>', views.soc_boardDelete, name='soc_delete'), 
    path('soc/edit/<int:postId>', views.soc_boardEdit, name='soc_boardEdit'), 
]

log_app/urls.py
from django.urls import path
from . import views

app_name = 'log_app'

urlpatterns = [
    path('', views.login_view, name='Login'),
    path('logout', views.logout_view, name='Logout'),
    path('signup', views.signup_view, name='Signup'),
    path('activate/<str:uidb64>/<str:token>/',views.activate,name="activate"),
]

my_page/urls.py
from django.urls import path
from . import views

app_name = 'my_page'

urlpatterns = [
    path('out/',views.out_view, name="out"),
    path('modify/',views.modify_view, name="modify"),
    path('modify_id',views.modify_id,name="modify_id"),
    path('modify_pw',views.modify_pw,name="modify_pw"),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index')
]

qnaBoard/urls.py
from django.urls import path
from . import views

app_name = 'qnaBoard'

urlpatterns = [
    path('', views.index, name='index'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
    path('answer/delete/<int:postId>/<int:answerId>/', views.answer_delete, name='answer_delete'),
    path('<int:postId>/', views.detail,name='detail'),
    path('write/', views.write, name='write'),
    path('delete/<int:postId>', views.boardDelete, name='delete'),
    path('edit/<int:postId>', views.boardEdit, name='boardEdit'),
    path('select/<int:postId>/<int:answerId>', views.selectAnswer, name='selectAnswer'),
]

templates/footer.html
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- Footer -->
	<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="https://www.kmu.ac.kr/uni/main/main.jsp"target='_blank'><i class="fa fa-angle-double-right"></i>계명대학교</a></li>
						<li><a href="https://portal.kmu.ac.kr" target='_blank'><i class="fa fa-angle-double-right"></i>에드워드포털</a></li>


					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="http://ctl.kmu.ac.kr/index.jsp" target='_blank'><i class="fa fa-angle-double-right"></i>교수학습지원시스템</a></li>
						<li><a href="https://sugang.kmu.ac.kr/servlet/Fip" target='_blank'><i class="fa fa-angle-double-right"></i>수강신청</a></li>    
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="https://library.kmu.ac.kr/" target='_blank'><i class="fa fa-angle-double-right"></i>동산도서관</a></li>
                        <li><a href="https://story.kmu.ac.kr/main.do" target='_blank'><i class="fa fa-angle-double-right"></i>스튜던트포털</a></li>
					</ul>
				</div>
			</div>

				<hr>

			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                          <span><a href="/serviceagreement/">&nbsp 이용약관 &nbsp</a></span>
                          <span><a href="/privacy/">&nbsp 개인정보처리방침 &nbsp</a></span>
                          <span><a href="/rules/">&nbsp 커뮤니티이용규칙 &nbsp</a></span>
                          <span><a href="#">&nbsp 문의하기 &nbsp</a></span>
                    <br>
					<p class="h6 mt-2 mb-3">© 2021. KM포털 Co. all rights reserved.</p>
				</div>
				<hr>
			</div>	
		</div>
	</section>
	<!-- ./Footer -->

templates/header.html
{% load static %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">  
  <div class="container-fluid">
      <a href="/"><img src="/static/images/KMportal.png"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" id="freeB" aria-current="page" href="{% url 'board:free_index' %}">&nbsp&nbsp자유게시판&nbsp&nbsp</a> <!-- url board:index >> board:free_index 변경-->
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle " id="lineB" onclick='active' href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            &nbsp&nbsp계열게시판&nbsp&nbsp
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'board:eng_index' %}">공학 게시판</a></li>
            <li><a class="dropdown-item" href="{% url 'board:sci_index' %}">자연과학 게시판</a></li>
            <li><a class="dropdown-item" href="{% url 'board:med_index' %}">의학/간호 게시판</a></li>
            <li><a class="dropdown-item" href="{% url 'board:art_index' %}">예체능 게시판</a></li>
            <li><a class="dropdown-item" href="{% url 'board:soc_index' %}">인문/사회 게시판</a></li>
          </ul>
        </li>
                  <li class="nav-item">
          <a class="nav-link " id="qnaB" onclick='' href="{% url 'qnaBoard:index' %}">&nbsp&nbsp질문이&nbsp&nbsp</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link " id="boormB" onclick='' href="{% url 'boormiBoard:index' %}">&nbsp&nbsp부르미&nbsp&nbsp</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link " id="newsB" onclick='' href="{% url 'news:index' %}">&nbsp&nbsp알리미&nbsp&nbsp</a>
        </li>
            {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link " id="myB" onclick='' href="{% url 'my_page:modify' %}">&nbsp&nbsp마이페이지&nbsp&nbsp</a>
        </li>
            {% endif %}
      </ul>
      <form class="d-flex">
                         {% if user.is_authenticated %}
          <div style="display:flex; align-items:center;">
               <p style="margin:0;"> {{user.username}}님 안녕하세요. 매너온도 : {{user.manner}}°C 내공 : {{user.naegong}}점</p>
          </div>                            
          <a class="nav-link btn-primary" style="background-color: #ffebb8; color: #171717; margin-left:10px;" href="{% url 'log_app:Logout' %}">&nbsp&nbsp로그아웃&nbsp&nbsp</a>

                {% else %}
 
          <a class="nav-link btn-primary" style="background-color: #ffebb8; color: #171717;" href="{% url 'log_app:Signup' %}">&nbsp&nbsp회원가입&nbsp&nbsp</a>
  
  
          <a class="nav-link btn-primary" style="background-color: #ffebb8; color: #171717; margin-left:10px;" href="{% url 'log_app:Login' %}">&nbsp&nbsp로그인&nbsp&nbsp</a>
   
        {% endif %}
      </form>
    </div>
  </div>
</nav>

templates/main.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <link rel="stylesheet" href="/static/css/footer.css" />
    <link rel="stylesheet" href="/static/css/board_pre.css" />
    <link rel="stylesheet" href="/static/css/common.css" />
    <link rel="stylesheet" href="/static/css/map.css" />
    <link rel="stylesheet" href="/static/css/mobile.css" />

    <title>KM포털</title>
    <style>
        
#board_img{
    width: 40% ;
    height: auto;
}

    </style>
</head>
<body>
    {% include "header.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
        {% include "footer.html" %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</body>
</html>