KM_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('news/',include('news.urls')),
    path('board/',include('board.urls')),
    path('login/', include('log_app.urls')),
    path('my_page/',include('my_page.urls')),
    path('qnaboard/',include('qnaBoard.urls')),
    path('boormiboard/',include('boormiBoard.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_page/urls.py
from django.urls import path
from . import views

app_name = 'my_page'

urlpatterns = [
    path('out/',views.out_view, name="out"),
    path('modify/',views.modify_view, name="modify"),
    path('modify_id',views.modify_id,name="modify_id"),
    path('modify_pw',views.modify_pw,name="modify_pw"),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index')
]

my_page/models.py
from django.db import models

# Create your models here.

my_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import check_password
from django.contrib.auth import authenticate, login, logout
from log_app.models import CustomUser
# Create your views here.


def out_view(request):
    if request.method == "POST":
        pw_del = request.POST["pw_del"]
        user = request.user
        if not check_password(pw_del, user.password):
            return render(request,"my_page/out.html", {'error': '비밀번호가 틀렸습니다.'}) 
        else:
            logout(request)
            user.delete()
            return render(request,"main.html")
    else:
        return render(request,'my_page/out.html')

def modify_view(request):
    return render(request,'my_page/modify.html')

def modify_id(request):
    if request.method == "POST":
        user = request.user
        if user.username == request.POST['change_ID']:
            return render(request,'my_page/modify.html',{'error_id':'같은 아이디로는 변경되지않습니다.'})
        else:
            userList = CustomUser.objects.all()
            for userl in userList:
                if userl.username == request.POST['change_ID']:
                    return render(request,'my_page/modify.html',{'error_id':'이미 동일한 계정이 존재합니다.'})
            user.username = request.POST['change_ID']
            user.save()
            return render(request,'main.html')
    else:
        return render(request,'main.html')

def modify_pw(request):
    if request.method == "POST":
        user = request.user
        old_password = request.POST['old_password']
        new_password1 = request.POST['new_password1']
        new_password2 = request.POST['new_password2']
        if check_password(old_password,user.password):
            if new_password1 == new_password2:
                user.set_password(new_password1)
                user.save()
                login(request,user)
                return render(request,'main.html')
            
            else:
                return render(request,'my_page/modify.html',{'error':'비밀번호가 다릅니다.'})
        else:
            return render(request,'my_page/modify.html',{'error':'비밀번호가 틀렸습니다.'})
    else:
        return render(request,'my_page/modify.html')
    

templates/my_page/modify.html
<!--
=========================================================
* Paper Dashboard 2 - v2.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-2
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!doctype html>
<html lang="en">
<head>
   {% load static %}
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="./assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Paper Dashboard 2 by Creative Tim
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" /> <!--./assets/css/bootstrap.min.css -->
  <link href="{% static 'css/paper-dashboard.css' %}" rel="stylesheet" /> <!--./assets/css/paper-dashboard.css?v=2.0.1-->
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
  <style>
    #frm2 {
      display : flex;
      flex-direction: column;
    }
    #change {
      margin-left : 10px;
    }
     #plus {
          visibility:hidden;
      }
      #home {
          visibility:hidden;
      }
@media screen and (max-width:700px) {
    #plus{
        visibility:visible;
        margin-left : 20px;
        }
    #home {
        visibility:visible;
        margin-left : 20px;
    }
}
  </style>
<script>

function check1() {

  if(fr1.change_ID.value == "") {

    alert("바꿀 아이디를 입력해주세요.");

    fr1.change_ID.focus();

    return false;
  }

  return true;
}

function check2() {

  if(fr2.old_password.value == "") {

    alert("현재 비밀번호를 입력해주세요.");

    fr2.old_password.focus();

    return false;
  }
    
  else if(fr2.new_password1.value == "") {
      
     alert("새 비밀번호를 입력해주세요.");
      
     fr2.new_password1.focus();
      
     return false;
  }
    
  else if(fr2.new_password2.value == "") {
      
     alert("비밀번호 확인을 위해 입력해주세요.");
      
     fr2.new_password2.focus();
      
     return false;
  }
  

 return true;
  
}
</script>
</head>

<body class="">
  <div class="wrapper">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <div class="logo">
        <a href="https://www.creative-tim.com" class="simple-text logo-mini">
          <!-- <div class="logo-image-small">
            <img src="./assets/img/logo-small.png">
          </div> -->
          <!-- <p>CT</p> -->
        </a>
        <a href="/" class="simple-text logo-normal">
          KM_POTAL
          <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{% url 'my_page:out' %}">
              <p>회원탈퇴</p>
            </a>
          </li>
          <li class ="active ">
            <a href="{% url 'my_page:modify' %}">
              <p>회원정보수정</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel" style="height: 100vh;">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand">회원정보수정</a>
            <a class="navbar-brand" id="plus" href="{% url 'my_page:out' %}">회원탈퇴</a>
            <a class="navbar-brand" id="home" href="/">KM_PORTAL</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
                <div class="input-group-append">
                  
                    
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item btn-rotate dropdown">
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <form method="POST" action="{% url 'my_page:modify_id' %}" id="frm1" name="fr1" onsubmit="return check1()">
              {% csrf_token %}
            <label>
              <p class="label-txt">아이디 변경</p>
              <input type="text" class="input" name="change_ID" minlength="3" maxlength="30">
                <button type="submit" id="change">변경하기</button>
                <br><br>
                {{error_id}}
              <div class="line-box">
                <hr>
              </div>
            </label>
            </form>
            <form method="POST" action="{% url 'my_page:modify_pw' %}" id="frm2" name= "fr2" onsubmit="return check2()">
              {% csrf_token %}
            <label>
              <p class="label-txt">현재 비밀번호</p>
              <input type="password" class="input" name="old_password" minlength="3">
              <div class="line-box">
                <div class="line"></div>
              </div>
            </label>
            <label>
              <p class="label-txt">새 비밀번호</p>
              <input type="password" class="input" name="new_password1" minlength="3">
              <div class="line-box">
                <div class="line"></div>
              </div>
            </label>
            <label>
              <p class="label-txt">비밀번호 확인</p>
              <input type="password" class="input" name="new_password2" minlength="3">
              <button type="submit" id="change">변경하기</button>
            </label>
            </form>
          </div>
        </div>
      </div>
      <footer class="footer" style="position: absolute; bottom: 0; width: -webkit-fill-available;">
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
</body>

</html>

templates/my_page/out.html
<!--
=========================================================
* Paper Dashboard 2 - v2.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-2
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!doctype html>
<html lang="en">

<head>
   {% load static %}
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="./assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Paper Dashboard 2 by Creative Tim
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" /> <!--./assets/css/bootstrap.min.css -->
  <link href="{% static 'css/paper-dashboard.css' %}" rel="stylesheet" /> <!--./assets/css/paper-dashboard.css?v=2.0.1-->
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
  <style>
    #except{
      margin-left : 10px;
    }
       #home{
               visibility:hidden;
                margin-left:20px;
          }
          #modify{
              visibility:hidden;
                margin-left:20px;
          }
      @media screen and (max-width:700px) {
          #home{
               visibility:visible;
                margin-left:20px;
          }
          #modify{
              visibility:visible;
                margin-left:20px;
          }
      }
  </style>
<script>
function check() {

  if(fr.pw_del.value == "") {

    alert("비밀번호 확인을 위해 비밀번호를 입력해주세요.    ");

    fr.pw_del.focus();

    return false;
  }

  return true;
}
</script>
</head>

<body class="">
  <div class="wrapper">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <div class="logo">
        <a href="https://www.creative-tim.com" class="simple-text logo-mini">
          <!-- <div class="logo-image-small">
            <img src="./assets/img/logo-small.png">
          </div> -->
          <!-- <p>CT</p> -->
        </a>
        <a href="/" class="simple-text logo-normal">
          KM_POTAL
          <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="active "> 
            <a href="{% url 'my_page:out' %}">
              <p>회원탈퇴</p>
            </a>
          </li>
          <li>
            <a href="{% url 'my_page:modify' %}">
              <p>회원정보수정</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel" style="height: 100vh;">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand">회원탈퇴</a>
            <a class="navbar-brand" id="modify" href="{%url 'my_page:modify'%}">회원정보수정</a>
            <a class="navbar-brand" id="home" href="/">KM_PORTAL</a>
          </div>
      <!--------필요없지만 지우면 안되는 코드------->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form text>
              <div class="input-group no-border">
                <div class="input-group-append">
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item btn-rotate dropdown">
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!--------필요없지만 지우면 안되는 코드------->
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <form action="{% url 'my_page:out' %}" method="POST" name="fr" onsubmit="return check()">
              {% csrf_token %}
              비밀번호 확인: <input type="text" name="pw_del" minlength="3">
                <button type="submit" id="except">회원탈퇴</button>
                <br><br><br>{{error}}
            </form>
          </div>
        </div>
      </div>
      <footer class="footer" style="position: absolute; bottom: 0; width: -webkit-fill-available;">
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
</body>

</html>