KM_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('news/',include('news.urls')),
    path('board/',include('board.urls')),
    path('login/', include('log_app.urls')),
    path('my_page/',include('my_page.urls')),
    path('qnaboard/',include('qnaBoard.urls')),
    path('boormiboard/',include('boormiBoard.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

log_app/urls.py
from django.urls import path
from . import views

app_name = 'log_app'

urlpatterns = [
    path('', views.login_view, name='Login'),
    path('logout', views.logout_view, name='Logout'),
    path('signup', views.signup_view, name='Signup'),
    path('activate/<str:uidb64>/<str:token>/',views.activate,name="activate"),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index')
]

log_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser

class CustomUser(AbstractUser):
    naegong = models.IntegerField(default=0, null=True)
    manner = models.IntegerField(default=0, null=True)
    def __str__(self):
        return self.username

log_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import CustomUser
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
# Create your views here.

def login_view(request) :
    if request.method == "POST":
        username = request.POST['ID']
        password = request.POST['Password']
        user = authenticate(request=request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'log_app/login.html', {'error': '아이디나 비밀번호가 틀렸습니다.'})
    else:
        return render(request, 'log_app/login.html')

def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    if request.method == "POST":
        if CustomUser.objects.filter(username=request.POST['username']).exists():
            return render(request, 'log_app/signup.html', {'error': '이 아이디로 가입한 계정이 존재합니다.'})
        
        elif CustomUser.objects.filter(email = str(request.POST['STUID'])+"@kmu.kr").exists():
             return render(request, 'log_app/signup.html', {'error': '이 이메일로 가입한 계정이 존재합니다.'})
            
        elif request.POST["password1"] == request.POST["password2"]:
            Email = str(request.POST['STUID'])+"@stu.kmu.ac.kr"
            user = CustomUser.objects.create_user(username=request.POST['username'], password=request.POST['password1'], email=Email)
            # user.is_active = False
            user.save()
            # current_site = get_current_site(request)
            # message = render_to_string('log_app/activation_email.html',{ 
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # mail_title = "계정 활성화 확인 이메일"
            # mail_to = request.POST["STUID"]+"@stu.kmu.ac.kr"
            # email = EmailMessage(mail_title,message,to=[mail_to])
            # email.send()
            return redirect('/')
        else:
            return render(request, 'log_app/signup.html', {'error': '비밀번호가 다릅니다.'})
    else:
        return render(request, 'log_app/signup.html')
    
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExsit):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('/')
    else:
        return render(request, 'home.html', {'error' : '계정 활성화 오류'})
    return 
    

templates/log_app/activation_email.html
{{user.username}}님 아래 링크를 클릭하여 계정을 활성화하세요 :
http://{{domain}}{% url 'log_app:activate' uid token %}

templates/log_app/login.html
<head>
<style>


.form-heading { color:#fff; font-size:23px;}
.panel {
    margin-bottom : 30px;
}
.panel h2{ color:#444444; font-size:18px; margin:0 0 8px 0;}
.panel p { color:#777777; font-size:14px; margin-bottom:30px; line-height:24px;}
.login-form .form-control {
  background: #f7f7f7 none repeat scroll 0 0;
  border: 1px solid #d4d4d4;
  border-radius: 4px;
  font-size: 14px;
  height: 50px;
  line-height: 50px;
}
.main-div {
  background: #ffffff none repeat scroll 0 0;
  border-radius: 2px;
  margin: 10px auto 30px;
  max-width: 38%;
  padding: 50px 70px 70px 71px;
}

.login-form .form-group {
  margin-bottom:10px;
}
.login-form{ text-align:center;}
.forgot a {
  color: #777777;
  font-size: 14px;
  text-decoration: underline;
}
.login-form  .btn.btn-primary {
  background: #f0ad4e none repeat scroll 0 0;
  border-color: #f0ad4e;
  color: #ffffff;
  font-size: 14px;
  width: 100%;
  height: 50px;
  line-height: 50px;
  padding: 0;
}
.forgot {
  flex-direction: row;
  text-align: left; 
  margin-bottom:30px;
}
.forgot a {
    margin-right: 10px;;
}
.botto-text {
  color: #ffffff;
  font-size: 14px;
  margin: auto;
}
.login-form .btn.btn-primary.reset {
  background: #ff9900 none repeat scroll 0 0;
}
.back { text-align: left; margin-top:10px;}
.back a {color: #444444; font-size: 13px;text-decoration: none;}

</style>
<script>

function check() {

  if(fr.ID.value == "") {

    alert("아이디와 비밀번호 모두 입력해주세요.");

    fr.ID.focus();

    return false;

  }
    
  else if(fr.Password.value=="") {
      alert("아이디와 비밀번호 모두 입력해주세요.");
      fr.Password.focus();
      return false;
  }
    
    return true;
}
    </script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
</head>
<body id="LoginForm">
<div class="container">
<div class="login-form">
<div class="main-div">
    <div class="panel">
   <h2 id="title"><a href='/'>KM_PORTAL</a></h2>
        <strong>{{error}}</strong>
   </div>
    <form id="Login" action="{% url 'log_app:Login' %}" method="POST" name="fr" onsubmit="return check();">
      {% csrf_token %}
        <div class="form-group">


            <input type="text" class="form-control" name="ID" placeholder="아이디">

        </div>

        <div class="form-group">

            <input type="password" class="form-control" name="Password" placeholder="비밀번호">

        </div>

        <div class="forgot">
            <a href="{% url 'log_app:Signup' %}">회원가입</a>
        </div>

        <button type="submit" class="btn btn-primary">로그인</button>

    </form>
    </div>
<p class="botto-text"> Designed by Sunil Rajput</p>
</div></div></div>


</body>
</html>

templates/log_app/signup.html
<style>
    body {
    background: #C5E1A5;
    }
    
h1 a, h1 a:hover, h1 a:visited, h1 a:active, h1 a:focus {
    color : rgb(120,120,120);
    text-decoration: none;
}
form {
  width: 60%;
  margin: 60px auto;
  background: #efefef;
  padding: 60px 120px 60px 120px;
  text-align: center;
  -webkit-box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
  box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
  display : flex;
  flex-direction: column;
}
#title {
    color : rgb(120,120,120);
}
label {
  display: block;
  position: relative;
  margin: 40px 0px;
}
.label-txt {
  position: absolute;
  top: -1.6em;
  padding: 10px;
  font-family: sans-serif;
  font-size: .8em;
  letter-spacing: 1px;
  color: rgb(120,120,120);
  transition: ease .3s;
}
.input {
  width: 100%;
  padding: 10px;
  background: transparent;
  border: none;
  outline: none;
}

.line-box {
  position: relative;
  width: 100%;
  height: 2px;
  background: #BCBCBC;
}

.line {
  position: absolute;
  width: 0%;
  height: 2px;
  top: 0px;
  left: 50%;
  transform: translateX(-50%);
  background: #8BC34A;
  transition: ease .6s;
}

.input:focus + .line-box .line {
  width: 100%;
}

.label-active {
  top: -3em;
}

button {
  display: inline-block;
  padding: 12px 24px;
  background: rgb(220,220,220);
  font-weight: bold;
  color: rgb(120,120,120);
  border: none;
  outline: none;
  border-radius: 3px;
  cursor: pointer;
  transition: ease .3s;
}

button:hover {
  background: #8BC34A;
  color: #ffffff;
}
</style>
<script>
    $(document).ready(function(){

$('.input').focus(function(){
  $(this).parent().find(".label-txt").addClass('label-active');
});

$(".input").focusout(function(){
  if ($(this).val() == '') {
    $(this).parent().find(".label-txt").removeClass('label-active');
  };
});
});
</script>
<script>

function check() {

  if(fr.username.value == "") {

    alert("모든 정보를 입력해야합니다.");

    fr.username.focus();

    return false;

  }

  else if(fr.password1.value == "") {

    alert("모든 정보를 입력해야합니다.");

    fr.password1.focus();

    return false;
      
  }
    
 else if(fr.password2.value == "") {

    alert("모든 정보를 입력해야합니다.");

    fr.password2.focus();

    return false;

  }
 else if(fr.STUID.value == "") {

    alert("모든 정보를 입력해야합니다.");

    fr.STUID.focus();

    return false;

  }
  else return true;

}

</script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!------ Include the above in your HEAD tag ---------->
<body>
<form method="POST" action="{% url 'log_app:Signup' %}" name="fr" onsubmit="return check()">
    {% csrf_token %}
    <h1 id="title"><a href='/'>KM_PORTAL</a></h1>
  <label>
    <p class="label-txt">아이디</p>
    <input type="text" class="input" name="username" minlength="3" maxlength="10">
    <div class="line-box">
      <div class="line"></div>
    </div>
  </label>
  <label>
    <p class="label-txt">비밀번호</p>
    <input type="password" class="input" name="password1" minlength="3" maxlength="64">
    <div class="line-box">
      <div class="line"></div>
    </div>
  </label>
  <label>
    <p class="label-txt">비밀번호 확인</p>
    <input type="password" class="input" name="password2" minlength="3" maxlength="64" onkeydown="onlyNumber(this)"
>
    <div class="line-box">
      <div class="line"></div>
    </div>
  </label>
  <label>
    <p class="label-txt">학번</p>
    <input type="text" name="STUID" class="input" placeholder="학번을 입력해주세요." minlength="7" maxlength="7" onKeyup="this.value=this.value.replace(/[^0-9]/g,'')">
    <div class="line-box">
      <div class="line"></div>
    </div>
  </label>
  <button type="submit">가입하기</button>
    <br>
    <strong>{{error}}</strong>
</form>